/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository.
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ObsidianRAGPlugin
});
module.exports = __toCommonJS(main_exports);
var import_child_process = require("child_process");
var import_obsidian = require("obsidian");
var VIEW_TYPE_CHAT = "obsidianrag-chat-view";
var DEFAULT_PORT = 8e3;
var MAX_RETRY_ATTEMPTS = 3;
var RETRY_DELAY_MS = 1e3;
var DEFAULT_SETTINGS = {
  pythonPath: "obsidianrag",
  serverPort: DEFAULT_PORT,
  llmProvider: "ollama",
  llmApiFormat: "ollama",
  llmModel: "gemma3",
  llmBaseUrl: "http://localhost:11434",
  llmApiKey: "lm-studio",
  autoStartServer: true,
  showSourceLinks: true,
  useReranker: true,
  hasCompletedSetup: false
};
var ObsidianRAGPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.serverProcess = null;
    this.apiBaseUrl = "";
    this.restartAttempts = 0;
    this.maxRestartAttempts = 3;
    this.isRestarting = false;
    this.statusBarItem = null;
    this._manualStop = false;
  }
  async onload() {
    console.debug("Loading ObsidianRAG plugin");
    await this.loadSettings();
    this.apiBaseUrl = `http://127.0.0.1:${this.settings.serverPort}`;
    this.registerView(VIEW_TYPE_CHAT, (leaf) => new ChatView(leaf, this));
    this.addRibbonIcon("message-circle", "Chat", () => {
      void this.activateChatView();
    });
    this.statusBarItem = this.addStatusBarItem();
    this.statusBarItem.addClass("obsidianrag-status-bar");
    this.statusBarItem.onClickEvent(() => {
      void this.handleStatusBarClick();
    });
    void this.updateStatusBar();
    this.addCommand({
      id: "open-chat",
      name: "Open chat",
      callback: () => {
        void this.activateChatView();
      }
    });
    this.addCommand({
      id: "start-server",
      name: "Start server",
      callback: () => {
        void this.startServer();
      }
    });
    this.addCommand({
      id: "stop-server",
      name: "Stop server",
      callback: () => {
        void this.stopServer();
      }
    });
    this.addCommand({
      id: "check-status",
      name: "Check status",
      callback: () => {
        void this.checkServerStatus();
      }
    });
    this.addCommand({
      id: "ask-question",
      name: "Ask a question",
      callback: () => new AskQuestionModal(this.app, this).open()
    });
    this.addCommand({
      id: "reindex-vault",
      name: "Reindex vault",
      callback: () => {
        void this.reindexVault();
      }
    });
    this.addSettingTab(new ObsidianRAGSettingTab(this.app, this));
    if (!this.settings.hasCompletedSetup) {
      new SetupModal(this.app, this).open();
    }
    if (this.settings.autoStartServer) {
      setTimeout(() => {
        void this.startServer();
      }, 2e3);
    }
    this.registerInterval(
      window.setInterval(() => {
        void this.updateStatusBar();
      }, 1e4)
    );
  }
  onunload() {
    console.debug("Unloading ObsidianRAG plugin");
    void this.stopServer();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.apiBaseUrl = `http://127.0.0.1:${this.settings.serverPort}`;
  }
  // ==========================================================================
  // Status Bar
  // ==========================================================================
  async handleStatusBarClick() {
    if (await this.isServerRunning()) {
      void this.activateChatView();
    } else {
      void this.startServer();
    }
  }
  async updateStatusBar() {
    if (!this.statusBarItem) return;
    const running = await this.isServerRunning();
    this.statusBarItem.empty();
    if (running) {
      this.statusBarItem.setText("RAG *");
      this.statusBarItem.setAttribute("title", "Vault RAG: online - click to open chat");
      this.statusBarItem.addClass("status-online");
      this.statusBarItem.removeClass("status-offline");
    } else {
      this.statusBarItem.setText("RAG -");
      this.statusBarItem.setAttribute("title", "Vault RAG: offline - click to start server");
      this.statusBarItem.addClass("status-offline");
      this.statusBarItem.removeClass("status-online");
    }
  }
  // ==========================================================================
  // View Management
  // ==========================================================================
  async activateChatView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_CHAT)[0];
    if (!leaf) {
      const rightLeaf = workspace.getRightLeaf(false);
      if (rightLeaf) {
        leaf = rightLeaf;
        await leaf.setViewState({ type: VIEW_TYPE_CHAT, active: true });
      }
    }
    if (leaf) {
      await workspace.revealLeaf(leaf);
    }
  }
  // ==========================================================================
  // Server Management
  // ==========================================================================
  async startServer() {
    var _a, _b;
    if (await this.isServerRunning()) {
      new import_obsidian.Notice("Vault RAG server is already running");
      return true;
    }
    new import_obsidian.Notice("Starting Vault RAG server...");
    try {
      const vaultPath = this.app.vault.adapter.basePath;
      const platform = process.platform;
      const spawnOptions = this.getSpawnOptionsForPlatform(platform);
      let command;
      let args;
      if (platform === "win32") {
        command = this.settings.pythonPath;
        args = [
          "serve",
          "--vault",
          `"${vaultPath}"`,
          // Quote path for Windows
          "--port",
          String(this.settings.serverPort),
          "--provider",
          this.settings.llmProvider,
          "--model",
          this.settings.llmModel,
          "--base-url",
          this.settings.llmBaseUrl,
          "--api-format",
          this.settings.llmApiFormat,
          this.settings.useReranker ? "--reranker" : "--no-reranker"
        ];
        if (this.settings.llmApiKey) {
          args.push("--api-key", this.settings.llmApiKey);
        }
      } else {
        command = this.settings.pythonPath;
        args = [
          "serve",
          "--vault",
          vaultPath,
          "--port",
          String(this.settings.serverPort),
          "--provider",
          this.settings.llmProvider,
          "--model",
          this.settings.llmModel,
          "--base-url",
          this.settings.llmBaseUrl,
          "--api-format",
          this.settings.llmApiFormat,
          this.settings.useReranker ? "--reranker" : "--no-reranker"
        ];
        if (this.settings.llmApiKey) {
          args.push("--api-key", this.settings.llmApiKey);
        }
      }
      this.serverProcess = (0, import_child_process.spawn)(command, args, spawnOptions);
      (_a = this.serverProcess.stdout) == null ? void 0 : _a.on("data", (data) => {
        console.debug(`[ObsidianRAG] ${data.toString()}`);
      });
      (_b = this.serverProcess.stderr) == null ? void 0 : _b.on("data", (data) => {
        console.error(`[ObsidianRAG] ${data.toString()}`);
      });
      this.serverProcess.on("error", (error) => {
        console.error("[ObsidianRAG] Process error:", error);
        new import_obsidian.Notice(`Failed to start server: ${error.message}`);
      });
      this.serverProcess.on("exit", (code) => {
        console.debug(`[ObsidianRAG] Server exited with code ${code}`);
        this.serverProcess = null;
        if (this._manualStop) {
          this._manualStop = false;
          return;
        }
        if (this.settings.autoStartServer && !this.isRestarting) {
          void this.handleServerCrash(code);
        }
      });
      const ready = await this.waitForServer(3e4);
      if (ready) {
        this.restartAttempts = 0;
        new import_obsidian.Notice("Vault RAG server started successfully!");
        void this.updateStatusBar();
        return true;
      } else {
        new import_obsidian.Notice("Server started but not responding. Check logs.");
        return false;
      }
    } catch (error) {
      console.error("[ObsidianRAG] Failed to start server:", error);
      new import_obsidian.Notice(`Failed to start server: ${error}`);
      return false;
    }
  }
  async handleServerCrash(exitCode) {
    if (this.restartAttempts >= this.maxRestartAttempts) {
      new import_obsidian.Notice(`Server crashed ${this.maxRestartAttempts} times. Please check logs and restart manually.`);
      this.restartAttempts = 0;
      return;
    }
    this.restartAttempts++;
    this.isRestarting = true;
    const delay = RETRY_DELAY_MS * this.restartAttempts;
    new import_obsidian.Notice(`Server exited with code ${exitCode}. Restarting in ${delay / 1e3}s... (attempt ${this.restartAttempts}/${this.maxRestartAttempts})`);
    await new Promise((resolve) => setTimeout(resolve, delay));
    this.isRestarting = false;
    await this.startServer();
  }
  async stopServer() {
    this._manualStop = true;
    if (this.serverProcess) {
      this.serverProcess.kill();
      this.serverProcess = null;
    }
    try {
      const platform = process.platform;
      const killCmd = platform === "win32" ? `for /f "tokens=5" %a in ('netstat -aon ^| find ":${this.settings.serverPort}" ^| find "LISTENING"') do taskkill /F /PID %a` : `lsof -ti:${this.settings.serverPort} | xargs kill -9 2>/dev/null`;
      await new Promise((resolve) => {
        (0, import_child_process.exec)(killCmd, (error) => {
          if (error) console.debug("[ObsidianRAG] No process found on port");
          resolve();
        });
      });
    } catch (e) {
      console.debug("[ObsidianRAG] Could not kill process by port:", e);
    }
    new import_obsidian.Notice("Vault RAG server stopped");
    void this.updateStatusBar();
  }
  async isServerRunning() {
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url: `${this.apiBaseUrl}/health`,
        method: "GET"
      });
      return response.status >= 200 && response.status < 300;
    } catch (e) {
      return false;
    }
  }
  /**
   * Fetch available models from the configured local provider.
   */
  async getProviderModels() {
    try {
      const url = this.getModelListUrl();
      const response = await (0, import_obsidian.requestUrl)({
        url,
        method: "GET",
        headers: this.settings.llmApiFormat === "chat-completions" ? { Authorization: `Bearer ${this.settings.llmApiKey || "lm-studio"}` } : void 0
      });
      if (response.status < 200 || response.status >= 300) {
        console.warn("[ObsidianRAG] Failed to fetch provider models");
        return [];
      }
      const data = response.json;
      if (Array.isArray(data.data)) {
        return data.data.map((m) => m.id).filter(Boolean);
      }
      if (Array.isArray(data.models)) {
        return data.models.map((m) => (m.id || m.name).replace(":latest", "")).filter(Boolean);
      }
      return [];
    } catch (error) {
      console.warn("[ObsidianRAG] Provider model list not available:", error);
      return [];
    }
  }
  getModelListUrl() {
    const baseUrl = this.settings.llmBaseUrl.replace(/\/$/, "");
    if (this.settings.llmProvider === "ollama" || this.settings.llmApiFormat === "ollama") {
      return `${baseUrl}/api/tags`;
    }
    return `${baseUrl}/models`;
  }
  async waitForServer(timeout) {
    const start = Date.now();
    while (Date.now() - start < timeout) {
      if (await this.isServerRunning()) {
        return true;
      }
      await new Promise((resolve) => setTimeout(resolve, 500));
    }
    return false;
  }
  async checkServerStatus() {
    try {
      const response = await (0, import_obsidian.requestUrl)(`${this.apiBaseUrl}/health`);
      if (response.status >= 200 && response.status < 300) {
        const data = response.json;
        new import_obsidian.Notice(
          `Server OK
Version: ${data.version}
Model: ${data.model}`
        );
      } else {
        new import_obsidian.Notice("Server responded but with an error");
      }
    } catch (e) {
      new import_obsidian.Notice("Server is not running");
    }
  }
  // ==========================================================================
  // API Methods
  // ==========================================================================
  async askQuestion(question) {
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url: `${this.apiBaseUrl}/ask`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text: question })
      });
      if (response.status < 200 || response.status >= 300) {
        throw new Error(`Server error: ${response.status}`);
      }
      return response.json;
    } catch (error) {
      return {
        result: "",
        sources: [],
        question: "",
        process_time: 0,
        session_id: "",
        error: `Failed to get answer: ${error}`
      };
    }
  }
  /**
   * Ask a question with streaming-like events using Obsidian's requestUrl
   * Note: True streaming is not supported by requestUrl, so we simulate events
   */
  async *askQuestionStreaming(question) {
    var _a, _b;
    try {
      yield { type: "start", session_id: "" };
      yield { type: "status", message: "Sending question..." };
      const response = await (0, import_obsidian.requestUrl)({
        url: `${this.apiBaseUrl}/ask`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text: question })
      });
      if (response.status < 200 || response.status >= 300) {
        yield { type: "error", message: `Server error: ${response.status}` };
        return;
      }
      const data = response.json;
      if (data.error) {
        yield { type: "error", message: data.error };
        return;
      }
      yield {
        type: "retrieve_complete",
        docs_count: ((_a = data.sources) == null ? void 0 : _a.length) || 0,
        sources: ((_b = data.sources) == null ? void 0 : _b.map((s) => ({ source: s.source, score: s.score }))) || []
      };
      yield { type: "token", content: data.result };
      yield {
        type: "answer",
        question: data.question,
        answer: data.result,
        sources: data.sources || [],
        process_time: data.process_time
      };
      yield { type: "done" };
    } catch (error) {
      yield { type: "error", message: `Request error: ${error}` };
    }
  }
  /**
   * Get vault statistics from the server
   */
  async getStats() {
    return await this.fetchWithRetry(`${this.apiBaseUrl}/stats`);
  }
  /**
   * Trigger vault reindexing
   */
  async reindexVault() {
    if (!await this.isServerRunning()) {
      new import_obsidian.Notice("Server is not running. Start it first.");
      return false;
    }
    new import_obsidian.Notice("Reindexing vault... This may take a while.");
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url: `${this.apiBaseUrl}/rebuild_db`,
        method: "POST"
      });
      if (response.status >= 200 && response.status < 300) {
        const data = response.json;
        new import_obsidian.Notice(`Reindexing complete! Indexed ${data.total_chunks || "unknown"} chunks.`);
        return true;
      } else {
        new import_obsidian.Notice(`Reindexing failed: ${response.status}`);
        return false;
      }
    } catch (error) {
      new import_obsidian.Notice(`Reindexing failed: ${error}`);
      return false;
    }
  }
  /**
   * Fetch with retry logic
   */
  async fetchWithRetry(url, options = {}, attempts = MAX_RETRY_ATTEMPTS) {
    let lastError = null;
    for (let i = 0; i < attempts; i++) {
      try {
        const response = await (0, import_obsidian.requestUrl)({
          url,
          ...options
        });
        if (response.status >= 200 && response.status < 300) {
          return response.json;
        }
        lastError = new Error(`HTTP ${response.status}`);
      } catch (error) {
        lastError = error;
        if (i < attempts - 1) {
          await new Promise((resolve) => setTimeout(resolve, RETRY_DELAY_MS * (i + 1)));
        }
      }
    }
    console.error(`[ObsidianRAG] Failed after ${attempts} attempts:`, lastError);
    return null;
  }
  /**
   * Get platform-specific spawn options
   */
  getSpawnOptionsForPlatform(platform) {
    const env = {
      ...process.env,
      OBSIDIANRAG_LLM_PROVIDER: this.settings.llmProvider,
      OBSIDIANRAG_LLM_API_FORMAT: this.settings.llmApiFormat,
      OBSIDIANRAG_LLM_MODEL: this.settings.llmModel,
      OBSIDIANRAG_COMPATIBLE_BASE_URL: this.settings.llmBaseUrl,
      OBSIDIANRAG_COMPATIBLE_API_KEY: this.settings.llmApiKey,
      OBSIDIANRAG_USE_RERANKER: this.settings.useReranker ? "true" : "false"
    };
    if (platform === "win32") {
      return {
        shell: true,
        env,
        windowsHide: true
      };
    } else if (platform === "linux") {
      return {
        shell: false,
        env
      };
    } else {
      return {
        shell: false,
        env
      };
    }
  }
  /**
   * Get default Python command based on platform
   */
  getDefaultPythonCommand() {
    const platform = process.platform;
    if (platform === "win32") {
      return "py -m obsidianrag";
    } else if (platform === "linux") {
      return "python3 -m obsidianrag";
    } else {
      return "obsidianrag";
    }
  }
};
var SetupModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.currentStep = 0;
    this.availableModels = [];
    this.plugin = plugin;
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("obsidianrag-setup-modal");
    new import_obsidian.Setting(contentEl).setName("Welcome to Vault RAG").setHeading();
    this.availableModels = await this.plugin.getProviderModels();
    this.contentEl_modal = contentEl.createDiv("setup-content");
    this.showStep(0);
  }
  showStep(step) {
    var _a;
    this.currentStep = step;
    this.contentEl_modal.empty();
    const steps = [
      () => this.renderRequirements(),
      () => this.renderConfiguration(),
      () => this.renderComplete()
    ];
    if (step < steps.length) {
      (_a = steps[step]) == null ? void 0 : _a.call(steps);
    }
  }
  renderRequirements() {
    const el = this.contentEl_modal;
    new import_obsidian.Setting(el).setName("Check requirements").setHeading();
    const requirements = el.createEl("ul");
    const li1 = requirements.createEl("li");
    li1.createEl("strong", { text: "Python 3.11+" });
    li1.appendText(" - Required for the backend");
    const li2 = requirements.createEl("li");
    li2.createEl("strong", { text: "obsidianrag" });
    li2.appendText(" package - ");
    li2.createEl("code", { text: "uv add obsidianrag" });
    const li3 = requirements.createEl("li");
    li3.createEl("strong", { text: "Ollama" });
    li3.appendText(" - Local model server from ");
    li3.createEl("a", { text: "ollama.ai", href: "https://ollama.ai" });
    const li4 = requirements.createEl("li");
    li4.appendText("At least one model installed - ");
    li4.createEl("code", { text: "ollama pull gemma3" });
    el.createEl("p", {
      text: "Make sure you have all requirements installed before proceeding.",
      cls: "setting-item-description"
    });
    const buttons = el.createDiv("modal-button-container");
    const nextBtn = buttons.createEl("button", { text: "Next \u2192", cls: "mod-cta" });
    nextBtn.addEventListener("click", () => this.showStep(1));
    const skipBtn = buttons.createEl("button", { text: "Skip setup" });
    skipBtn.addEventListener("click", () => this.completeSetup());
  }
  renderConfiguration() {
    const el = this.contentEl_modal;
    new import_obsidian.Setting(el).setName("Configuration").setHeading();
    new import_obsidian.Setting(el).setName("Backend command").setDesc("Command to start the backend, usually 'obsidianrag'").addText((text) => text.setValue(this.plugin.settings.pythonPath).onChange(async (value) => {
      this.plugin.settings.pythonPath = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(el).setName("Server port").addText((text) => text.setValue(String(this.plugin.settings.serverPort)).onChange(async (value) => {
      this.plugin.settings.serverPort = parseInt(value) || DEFAULT_PORT;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(el).setName("Model provider").setDesc("Local runtime used for answer generation").addDropdown((dropdown) => dropdown.addOption("ollama", "Ollama").addOption("lmstudio", "LM Studio").addOption("custom", "Custom").setValue(this.plugin.settings.llmProvider).onChange(async (value) => {
      this.plugin.settings.llmProvider = value;
      if (value === "ollama") {
        this.plugin.settings.llmApiFormat = "ollama";
        this.plugin.settings.llmBaseUrl = "http://localhost:11434";
      } else if (value === "lmstudio") {
        this.plugin.settings.llmApiFormat = "chat-completions";
        this.plugin.settings.llmBaseUrl = "http://localhost:1234/v1";
      }
      await this.plugin.saveSettings();
      this.availableModels = await this.plugin.getProviderModels();
      this.showStep(this.currentStep);
    }));
    new import_obsidian.Setting(el).setName("Server URL").addText((text) => text.setValue(this.plugin.settings.llmBaseUrl).onChange(async (value) => {
      this.plugin.settings.llmBaseUrl = value;
      await this.plugin.saveSettings();
    }));
    const modelSetting = new import_obsidian.Setting(el).setName("Model");
    if (this.availableModels.length > 0) {
      modelSetting.addDropdown((dropdown) => {
        this.availableModels.forEach((model) => {
          dropdown.addOption(model, model);
        });
        const currentModel = this.plugin.settings.llmModel;
        if (this.availableModels.includes(currentModel)) {
          dropdown.setValue(currentModel);
        } else if (this.availableModels.length > 0) {
          dropdown.setValue(this.availableModels[0]);
          this.plugin.settings.llmModel = this.availableModels[0];
          void this.plugin.saveSettings();
        }
        dropdown.onChange(async (value) => {
          this.plugin.settings.llmModel = value;
          await this.plugin.saveSettings();
        });
      });
    } else {
      modelSetting.setDesc("Could not list models. Enter the model name manually.").addText((text) => text.setPlaceholder("gemma3").setValue(this.plugin.settings.llmModel).onChange(async (value) => {
        this.plugin.settings.llmModel = value;
        await this.plugin.saveSettings();
      }));
    }
    new import_obsidian.Setting(el).setName("Auto-start server").setDesc("Start the backend automatically when Obsidian opens").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoStartServer).onChange(async (value) => {
      this.plugin.settings.autoStartServer = value;
      await this.plugin.saveSettings();
    }));
    const buttons = el.createDiv("modal-button-container");
    const backBtn = buttons.createEl("button", { text: "\u2190 back" });
    backBtn.addEventListener("click", () => this.showStep(0));
    const nextBtn = buttons.createEl("button", { text: "Finish \u2192", cls: "mod-cta" });
    nextBtn.addEventListener("click", () => this.showStep(2));
  }
  renderComplete() {
    const el = this.contentEl_modal;
    new import_obsidian.Setting(el).setName("Setup complete").setHeading();
    el.createEl("p", { text: "You're all set to use Vault RAG." });
    const tips = el.createEl("ul");
    tips.createEl("li", { text: "Click the chat icon in the ribbon to open the chat" });
    tips.createEl("li", { text: "Use Cmd/Ctrl+P and search 'ObsidianRAG' for all commands" });
    tips.createEl("li", { text: "First question may take a moment while the vault is indexed" });
    const buttons = el.createDiv("modal-button-container");
    const startBtn = buttons.createEl("button", { text: "Start server & open chat", cls: "mod-cta" });
    startBtn.addEventListener("click", async () => {
      await this.plugin.startServer();
      void this.completeSetup();
      void this.plugin.activateChatView();
    });
    const laterBtn = buttons.createEl("button", { text: "Maybe later" });
    laterBtn.addEventListener("click", () => {
      void this.completeSetup();
    });
  }
  async completeSetup() {
    this.plugin.settings.hasCompletedSetup = true;
    await this.plugin.saveSettings();
    this.close();
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var AskQuestionModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("obsidianrag-ask-modal");
    new import_obsidian.Setting(contentEl).setName("Ask Vault RAG").setHeading();
    this.inputEl = contentEl.createEl("textarea", {
      placeholder: "Ask a question about your notes...",
      cls: "obsidianrag-modal-input"
    });
    const buttonContainer = contentEl.createDiv("modal-button-container");
    const askBtn = buttonContainer.createEl("button", { text: "Ask", cls: "mod-cta" });
    askBtn.addEventListener("click", () => {
      void this.askQuestion();
    });
    const openChatBtn = buttonContainer.createEl("button", { text: "Open full chat" });
    openChatBtn.addEventListener("click", () => {
      this.close();
      void this.plugin.activateChatView();
    });
    this.resultEl = contentEl.createDiv("obsidianrag-modal-result");
    this.inputEl.focus();
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        void this.askQuestion();
      }
    });
  }
  async askQuestion() {
    const question = this.inputEl.value.trim();
    if (!question) return;
    if (!await this.plugin.isServerRunning()) {
      this.resultEl.setText("Server is not running. Start it first.");
      return;
    }
    this.resultEl.empty();
    this.resultEl.createDiv({ text: "Thinking...", cls: "loading" });
    try {
      let answer = "";
      for await (const event of this.plugin.askQuestionStreaming(question)) {
        if (event.type === "token") {
          answer += event.content;
        } else if (event.type === "answer") {
          answer = event.answer;
        } else if (event.type === "error") {
          this.resultEl.setText(`${event.message}`);
          return;
        }
      }
      this.resultEl.empty();
      void import_obsidian.MarkdownRenderer.render(
        this.app,
        answer,
        this.resultEl,
        "",
        this
      );
    } catch (error) {
      this.resultEl.setText(`Error: ${error}`);
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var ChatView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.messages = [];
    // Status element reference for periodic updates
    this.statusEl = null;
    this.statusInterval = null;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_CHAT;
  }
  getDisplayText() {
    return "Vault RAG";
  }
  getIcon() {
    return "message-circle";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("obsidianrag-chat-container");
    const header = container.createDiv("obsidianrag-header");
    header.createEl("span", { text: "Vault RAG", cls: "obsidianrag-header-title" });
    const headerControls = header.createDiv("obsidianrag-header-controls");
    const reindexBtn = headerControls.createEl("button", {
      cls: "obsidianrag-header-btn",
      attr: { "aria-label": "Reindex vault" }
    });
    reindexBtn.setText("Reindex");
    reindexBtn.addEventListener("click", async () => {
      await this.plugin.reindexVault();
    });
    const clearBtn = headerControls.createEl("button", {
      cls: "obsidianrag-header-btn",
      attr: { "aria-label": "Clear chat history" }
    });
    clearBtn.setText("Clear");
    clearBtn.addEventListener("click", () => this.clearHistory());
    this.statusEl = headerControls.createSpan("obsidianrag-status");
    await this.updateStatus();
    this.statusInterval = window.setInterval(() => {
      void this.updateStatus();
    }, 5e3);
    this.containerEl_messages = container.createDiv("obsidianrag-messages");
    this.addMessage({
      role: "assistant",
      content: "Hello! I can answer questions about your notes. What would you like to know?",
      timestamp: /* @__PURE__ */ new Date()
    });
    const inputContainer = container.createDiv("obsidianrag-input-container");
    this.inputEl = inputContainer.createEl("textarea", {
      placeholder: "Ask a question about your notes...",
      cls: "obsidianrag-input"
    });
    const sendButton = inputContainer.createEl("button", {
      text: "Send",
      cls: "obsidianrag-send-button"
    });
    sendButton.addEventListener("click", () => {
      void this.sendMessage();
    });
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        void this.sendMessage();
      }
    });
  }
  clearHistory() {
    this.messages = [];
    this.containerEl_messages.empty();
    this.addMessage({
      role: "assistant",
      content: "Chat history cleared. How can I help you?",
      timestamp: /* @__PURE__ */ new Date()
    });
  }
  async updateStatus() {
    if (!this.statusEl) return;
    const running = await this.plugin.isServerRunning();
    this.statusEl.empty();
    this.statusEl.removeClass("status-online", "status-offline");
    if (running) {
      this.statusEl.addClass("status-online");
      this.statusEl.setText("\u25CF online");
    } else {
      this.statusEl.addClass("status-offline");
      this.statusEl.setText("\u25CF offline");
    }
  }
  async sendMessage() {
    const question = this.inputEl.value.trim();
    if (!question) return;
    this.addMessage({
      role: "user",
      content: question,
      timestamp: /* @__PURE__ */ new Date()
    });
    this.inputEl.value = "";
    if (!await this.plugin.isServerRunning()) {
      this.addMessage({
        role: "assistant",
        content: "Server is not running. Use the command palette to start it, or enable auto-start in settings.",
        timestamp: /* @__PURE__ */ new Date()
      });
      return;
    }
    const progressEl = this.containerEl_messages.createDiv(
      "obsidianrag-message assistant loading"
    );
    const progressContent = progressEl.createDiv("progress-content");
    progressContent.createEl("strong", { text: "Starting..." });
    const updateProgress = (step, details) => {
      progressContent.empty();
      progressContent.createEl("strong", { text: step });
      if (details) {
        progressContent.createEl("br");
        progressContent.createSpan({ cls: "progress-details", text: details });
      }
      this.containerEl_messages.scrollTop = this.containerEl_messages.scrollHeight;
    };
    let streamingEl = null;
    let streamingContent = "";
    try {
      let finalAnswer = null;
      for await (const event of this.plugin.askQuestionStreaming(question)) {
        switch (event.type) {
          case "start":
            updateProgress("Connecting...");
            break;
          case "status":
            updateProgress(event.message);
            break;
          case "retrieve_complete":
            updateProgress(
              `Retrieved ${event.docs_count} documents`,
              event.sources.slice(0, 3).map(
                (s) => {
                  var _a;
                  return `\u2022 ${((_a = s.source.split("/").pop()) == null ? void 0 : _a.replace(".md", "")) || s.source}`;
                }
              ).join("<br>")
            );
            break;
          case "ttft":
            console.debug(`[ObsidianRAG] Time to First Token: ${event.seconds}s`);
            break;
          case "token": {
            if (!streamingEl) {
              progressEl.remove();
              streamingEl = this.containerEl_messages.createDiv(
                "obsidianrag-message assistant streaming"
              );
              const contentDiv = streamingEl.createDiv("message-content");
              contentDiv.createDiv("streaming-text streaming-content");
            }
            streamingContent += event.content;
            const textEl = streamingEl.querySelector(".streaming-text");
            if (textEl) {
              textEl.empty();
              void import_obsidian.MarkdownRenderer.render(
                this.app,
                streamingContent,
                textEl,
                "",
                this
              );
            }
            this.containerEl_messages.scrollTop = this.containerEl_messages.scrollHeight;
            break;
          }
          case "generate_complete":
            if (!streamingEl) {
              updateProgress(
                "Generating answer...",
                event.answer_preview.substring(0, 100) + "..."
              );
            }
            break;
          case "answer":
            finalAnswer = event;
            break;
          case "error":
            progressEl.remove();
            if (streamingEl) streamingEl.remove();
            this.addMessage({
              role: "assistant",
              content: `Error: ${event.message}`,
              timestamp: /* @__PURE__ */ new Date()
            });
            return;
          case "done":
            break;
        }
      }
      if (progressEl.parentElement) {
        progressEl.remove();
      }
      if (finalAnswer) {
        const vaultPath = this.app.vault.adapter.basePath;
        const sourcesWithScores = [];
        for (const s of finalAnswer.sources || []) {
          let source = s.source;
          if (source.startsWith(vaultPath)) {
            source = source.substring(vaultPath.length);
            if (source.startsWith("/")) {
              source = source.substring(1);
            }
          }
          let displayPath = source;
          if (displayPath.endsWith(".md")) {
            displayPath = displayPath.substring(0, displayPath.length - 3);
          }
          const fileWithMd = source.endsWith(".md") ? source : source + ".md";
          const file = this.app.vault.getAbstractFileByPath(fileWithMd) || this.app.vault.getAbstractFileByPath(source);
          if (file) {
            sourcesWithScores.push({
              path: displayPath,
              displayName: displayPath.split("/").pop() || displayPath,
              score: s.score,
              exists: true
            });
          } else {
            const baseName = displayPath.split("/").pop() || displayPath;
            const allFiles = this.app.vault.getMarkdownFiles();
            const matchingFile = allFiles.find(
              (f) => f.basename.toLowerCase() === baseName.toLowerCase()
            );
            if (matchingFile) {
              const matchPath = matchingFile.path.endsWith(".md") ? matchingFile.path.substring(0, matchingFile.path.length - 3) : matchingFile.path;
              sourcesWithScores.push({
                path: matchPath,
                displayName: matchingFile.basename,
                score: s.score,
                exists: true
              });
            } else {
              console.debug(`[ObsidianRAG] Skipping non-existent source: ${displayPath}`);
            }
          }
        }
        const seen = /* @__PURE__ */ new Set();
        const uniqueSorted = sourcesWithScores.filter((s) => s.exists !== false).sort((a, b) => b.score - a.score).filter((s) => {
          if (seen.has(s.path)) return false;
          seen.add(s.path);
          return true;
        });
        if (streamingEl) {
          streamingEl.removeClass("streaming");
          const textEl = streamingEl.querySelector(".streaming-text");
          if (textEl) {
            textEl.removeClass("streaming-content");
            textEl.empty();
            void import_obsidian.MarkdownRenderer.render(
              this.app,
              finalAnswer.answer,
              textEl,
              "",
              this
            );
          }
          if (uniqueSorted.length > 0 && this.plugin.settings.showSourceLinks) {
            const sourcesEl = streamingEl.createDiv("message-sources");
            sourcesEl.createEl("strong", { text: "Sources (by relevance): " });
            uniqueSorted.forEach((source, i) => {
              if (i > 0) sourcesEl.appendText(" ");
              const sourceContainer = sourcesEl.createSpan("source-item");
              const scoreIndicator = this.getScoreIndicator(source.score);
              sourceContainer.appendText(scoreIndicator);
              if (source.exists !== false) {
                const link = sourceContainer.createEl("a", {
                  text: source.displayName,
                  cls: "internal-link"
                });
                link.addEventListener("click", (e) => {
                  e.preventDefault();
                  void this.app.workspace.openLinkText(source.path, "");
                });
              } else {
                sourceContainer.createSpan({
                  text: source.displayName,
                  cls: "source-not-found"
                });
              }
            });
          }
          this.messages.push({
            role: "assistant",
            content: finalAnswer.answer,
            sources: uniqueSorted,
            timestamp: /* @__PURE__ */ new Date()
          });
        } else {
          this.addMessage({
            role: "assistant",
            content: finalAnswer.answer,
            sources: uniqueSorted,
            timestamp: /* @__PURE__ */ new Date()
          });
        }
      }
    } catch (error) {
      progressEl.remove();
      this.addMessage({
        role: "assistant",
        content: `Error: ${error}`,
        timestamp: /* @__PURE__ */ new Date()
      });
    }
  }
  addMessage(message) {
    this.messages.push(message);
    const messageEl = this.containerEl_messages.createDiv(
      `obsidianrag-message ${message.role}`
    );
    const contentEl = messageEl.createDiv("message-content");
    void import_obsidian.MarkdownRenderer.render(
      this.app,
      message.content,
      contentEl,
      "",
      this
    );
    if (message.sources && message.sources.length > 0 && this.plugin.settings.showSourceLinks) {
      const sourcesEl = messageEl.createDiv("message-sources");
      sourcesEl.createEl("strong", { text: "Sources (by relevance): " });
      message.sources.forEach((source, i) => {
        if (i > 0) sourcesEl.appendText(" ");
        const sourceContainer = sourcesEl.createSpan("source-item");
        const scoreIndicator = this.getScoreIndicator(source.score);
        sourceContainer.appendText(scoreIndicator);
        if (source.exists !== false) {
          const link = sourceContainer.createEl("a", {
            text: source.displayName,
            cls: "internal-link"
          });
          link.setAttribute("title", `Relevance: ${(source.score * 100).toFixed(1)}%`);
          link.addEventListener("click", (e) => {
            e.preventDefault();
            void this.app.workspace.openLinkText(source.path, "");
          });
        } else {
          const span = sourceContainer.createSpan({
            text: source.displayName,
            cls: "source-not-found"
          });
          span.setAttribute("title", `File not found in vault`);
        }
      });
    }
    this.containerEl_messages.scrollTop = this.containerEl_messages.scrollHeight;
  }
  /**
   * Get a text indicator based on the relevance score
   */
  getScoreIndicator(score) {
    if (score >= 0.8) return "[++]";
    if (score >= 0.6) return "[+]";
    if (score >= 0.4) return "[~]";
    return "[-]";
  }
  async onClose() {
    if (this.statusInterval) {
      window.clearInterval(this.statusInterval);
      this.statusInterval = null;
    }
    this.statusEl = null;
    await Promise.resolve();
  }
};
var ObsidianRAGSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.statusRefreshInterval = null;
    this.availableModels = [];
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    void this.plugin.getProviderModels().then((models) => {
      this.availableModels = models;
      this.renderSettings(containerEl);
    });
  }
  renderSettings(containerEl) {
    containerEl.empty();
    void this.renderServerStatus(containerEl);
    new import_obsidian.Setting(containerEl).setName("Configuration").setHeading();
    new import_obsidian.Setting(containerEl).setName("Backend command").setDesc("Command to start the backend, usually 'obsidianrag'").addText(
      (text) => text.setPlaceholder("obsidianrag").setValue(this.plugin.settings.pythonPath).onChange(async (value) => {
        this.plugin.settings.pythonPath = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Server port").setDesc("Port for the backend API server").addText(
      (text) => text.setPlaceholder("8000").setValue(String(this.plugin.settings.serverPort)).onChange(async (value) => {
        const port = parseInt(value) || DEFAULT_PORT;
        this.plugin.settings.serverPort = port;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Model provider").setDesc("Runtime used for answer generation").addDropdown(
      (dropdown) => dropdown.addOption("ollama", "Ollama").addOption("lmstudio", "LM Studio").addOption("custom", "Custom").setValue(this.plugin.settings.llmProvider).onChange(async (value) => {
        this.plugin.settings.llmProvider = value;
        if (value === "ollama") {
          this.plugin.settings.llmApiFormat = "ollama";
          this.plugin.settings.llmBaseUrl = "http://localhost:11434";
        } else if (value === "lmstudio") {
          this.plugin.settings.llmApiFormat = "chat-completions";
          this.plugin.settings.llmBaseUrl = "http://localhost:1234/v1";
        }
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (this.plugin.settings.llmProvider === "custom") {
      new import_obsidian.Setting(containerEl).setName("API format").setDesc("Protocol spoken by the custom server").addDropdown(
        (dropdown) => dropdown.addOption("ollama", "Ollama").addOption("chat-completions", "Chat completions").setValue(this.plugin.settings.llmApiFormat).onChange(async (value) => {
          this.plugin.settings.llmApiFormat = value;
          await this.plugin.saveSettings();
          this.display();
        })
      );
    }
    new import_obsidian.Setting(containerEl).setName("Server URL").setDesc("Provider endpoint, for example Ollama or LM Studio local server").addText(
      (text) => text.setPlaceholder(this.plugin.settings.llmApiFormat === "ollama" ? "http://localhost:11434" : "http://localhost:1234/v1").setValue(this.plugin.settings.llmBaseUrl).onChange(async (value) => {
        this.plugin.settings.llmBaseUrl = value;
        await this.plugin.saveSettings();
      })
    );
    if (this.plugin.settings.llmApiFormat === "chat-completions") {
      new import_obsidian.Setting(containerEl).setName("API key").setDesc("Optional. LM Studio accepts any value.").addText(
        (text) => text.setPlaceholder("lm-studio").setValue(this.plugin.settings.llmApiKey).onChange(async (value) => {
          this.plugin.settings.llmApiKey = value;
          await this.plugin.saveSettings();
        })
      );
    }
    const modelSetting = new import_obsidian.Setting(containerEl).setName("Model").setDesc("Model to use for answering questions");
    if (this.availableModels.length > 0) {
      modelSetting.addDropdown((dropdown) => {
        this.availableModels.forEach((model) => {
          dropdown.addOption(model, model);
        });
        const currentModel = this.plugin.settings.llmModel;
        if (this.availableModels.includes(currentModel)) {
          dropdown.setValue(currentModel);
        } else if (this.availableModels.length > 0) {
          dropdown.setValue(this.availableModels[0]);
          this.plugin.settings.llmModel = this.availableModels[0];
          void this.plugin.saveSettings();
          new import_obsidian.Notice(`Model '${currentModel}' not found. Switched to '${this.availableModels[0]}'`);
        }
        dropdown.onChange(async (value) => {
          this.plugin.settings.llmModel = value;
          await this.plugin.saveSettings();
        });
      });
    } else {
      modelSetting.setDesc("Could not list models. Enter the model name manually.").addText(
        (text) => text.setPlaceholder("gemma3").setValue(this.plugin.settings.llmModel).onChange(async (value) => {
          this.plugin.settings.llmModel = value;
          await this.plugin.saveSettings();
        })
      );
    }
    new import_obsidian.Setting(containerEl).setName("Retrieval").setHeading();
    new import_obsidian.Setting(containerEl).setName("Use reranker").setDesc("Enable cross-encoder reranking for better relevance (slower but more accurate)").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.useReranker).onChange(async (value) => {
        this.plugin.settings.useReranker = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Auto-start server").setDesc("Automatically start the backend when Obsidian opens").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoStartServer).onChange(async (value) => {
        this.plugin.settings.autoStartServer = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Show source links").setDesc("Display links to source notes in answers").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showSourceLinks).onChange(async (value) => {
        this.plugin.settings.showSourceLinks = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Server controls").setHeading();
    new import_obsidian.Setting(containerEl).setName("Start server").setDesc("Manually start the backend server").addButton(
      (button) => button.setButtonText("Start").onClick(async () => {
        await this.plugin.startServer();
        this.display();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Stop server").setDesc("Stop the backend server").addButton(
      (button) => button.setButtonText("Stop").onClick(async () => {
        await this.plugin.stopServer();
        this.display();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Reindex vault").setDesc("Force reindex all notes in the vault").addButton(
      (button) => button.setButtonText("Reindex").setWarning().onClick(async () => {
        await this.plugin.reindexVault();
      })
    );
    void this.renderVaultStats(containerEl);
    new import_obsidian.Setting(containerEl).setName("Requirements").setHeading();
    const helpEl = containerEl.createEl("div", { cls: "setting-item-description" });
    helpEl.createEl("p", { text: "This plugin requires:" });
    const ul = helpEl.createEl("ul");
    const hLi1 = ul.createEl("li");
    hLi1.createEl("strong", { text: "Python 3.11+" });
    hLi1.appendText(" installed and accessible");
    const hLi2 = ul.createEl("li");
    hLi2.createEl("strong", { text: "obsidianrag" });
    hLi2.appendText(" package: ");
    hLi2.createEl("code", { text: "uv add obsidianrag" });
    const hLi3 = ul.createEl("li");
    hLi3.createEl("strong", { text: "Ollama" });
    hLi3.appendText(" running locally with at least one model");
    const pLink = helpEl.createEl("p", { text: "Install Ollama from " });
    pLink.createEl("a", { text: "ollama.ai", href: "https://ollama.ai" });
    new import_obsidian.Setting(containerEl).setName("Advanced").setHeading();
    new import_obsidian.Setting(containerEl).setName("Reset to defaults").setDesc("Reset all settings to their default values").addButton(
      (button) => button.setButtonText("Reset all settings").setWarning().onClick(async () => {
        const keepSetupComplete = this.plugin.settings.hasCompletedSetup;
        this.plugin.settings = {
          ...DEFAULT_SETTINGS,
          hasCompletedSetup: keepSetupComplete
        };
        await this.plugin.saveSettings();
        new import_obsidian.Notice("Settings reset to defaults");
        this.display();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Reset setup wizard").setDesc("Show the setup wizard again on next reload").addButton(
      (button) => button.setButtonText("Reset wizard").onClick(async () => {
        this.plugin.settings.hasCompletedSetup = false;
        await this.plugin.saveSettings();
        new import_obsidian.Notice("Setup wizard will show on next reload");
      })
    );
  }
  async renderServerStatus(containerEl) {
    const statusContainer = containerEl.createDiv("obsidianrag-settings-status");
    new import_obsidian.Setting(statusContainer).setName("Server status").setHeading();
    const statusEl = statusContainer.createDiv("status-display");
    await this.updateServerStatusDisplay(statusEl);
    if (this.statusRefreshInterval) {
      window.clearInterval(this.statusRefreshInterval);
    }
    this.statusRefreshInterval = window.setInterval(async () => {
      await this.updateServerStatusDisplay(statusEl);
    }, 3e3);
  }
  async updateServerStatusDisplay(statusEl) {
    const running = await this.plugin.isServerRunning();
    statusEl.removeClass("status-online", "status-offline");
    statusEl.empty();
    if (running) {
      statusEl.addClass("status-online");
      statusEl.createSpan({ cls: "status-indicator", text: "\u25CF" });
      statusEl.createSpan({ cls: "status-text", text: " Server is running" });
      try {
        const response = await (0, import_obsidian.requestUrl)(`http://127.0.0.1:${this.plugin.settings.serverPort}/health`);
        if (response.status >= 200 && response.status < 300) {
          const health = response.json;
          const detailsEl = statusEl.createDiv("status-details");
          detailsEl.createDiv({ text: `Version: ${health.version || "unknown"}` });
          detailsEl.createDiv({ text: `Model: ${health.model || "unknown"}` });
        }
      } catch (e) {
      }
    } else {
      statusEl.addClass("status-offline");
      statusEl.createSpan({ cls: "status-indicator", text: "\u25CF" });
      statusEl.createSpan({ cls: "status-text", text: " Server is offline" });
    }
  }
  async renderVaultStats(containerEl) {
    new import_obsidian.Setting(containerEl).setName("Vault statistics").setHeading();
    const statsContainer = containerEl.createDiv("obsidianrag-vault-stats");
    const running = await this.plugin.isServerRunning();
    if (!running) {
      statsContainer.setText("Start the server to view vault statistics.");
      return;
    }
    statsContainer.setText("Loading statistics...");
    const stats = await this.plugin.getStats();
    if (stats && !stats.error) {
      statsContainer.empty();
      const table = statsContainer.createEl("table", { cls: "stats-table" });
      const rows = [
        ["Total notes", String(stats.total_notes)],
        ["Total chunks", String(stats.total_chunks)],
        ["Total words", String(stats.total_words).replace(/\B(?=(\d{3})+(?!\d))/g, ",")],
        ["Avg words/chunk", String(stats.avg_words_per_chunk)],
        ["Folders", String(stats.folders)],
        ["Internal links", String(stats.internal_links)],
        ["Vault", stats.vault_path]
      ];
      rows.forEach(([label, value]) => {
        const row = table.createEl("tr");
        row.createEl("td", { text: label, cls: "stats-label" });
        row.createEl("td", { text: value, cls: "stats-value" });
      });
    } else {
      statsContainer.setText((stats == null ? void 0 : stats.error) || "Could not load statistics.");
    }
  }
  hide() {
    if (this.statusRefreshInterval) {
      window.clearInterval(this.statusRefreshInterval);
      this.statusRefreshInterval = null;
    }
  }
};
